baseurl = "https://davidneko.github.io/"
title = "Dav Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
# disqusShortname = "davwang"
# googleAnalytics = "UA-127976457-1"
# preserveTaxonomyNames = true
# paginate = 5 #frontpage pagination
# hasCJKLanguage = true
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]


[params]
  header_image = "img/header_002.jpg"
  SEOTitle = "Dav的博客 | Dav's Blog"
  description = "Dav 程序员，日语，英语 | 这里是 Dav 的博客， Hello World!"
  keyword = "DavidWang, Daveedo, 王大卫的博客， 网络博客，学习笔记"
  slogan = "Learn or burn"

  image_404 = "img/404-bg.jpg"
  # title_404 = "你来到了没有知识的荒原 :("


  # leancloud storage for page view counter
  page_view_conter = true
  leancloud_app_id = "mhwJ3ndaGLLrMFNj3CrmfYzC-gzGzoHsz"
  leancloud_app_key = "pmFzNNfgO0Hlzsy59Wu58Tr7"

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Developer, Whisky Lover, Learner for Life"
  sidebar_avatar = "img/PicolasCage.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  #wechat pay & alipay 
  reward = false
  # reward_guide = "如果这篇文章对你有用，请随意打赏" 

  [params.social]
  rss            = true 
  email          = "davidandneko233@gmail.com"
  facebook       = "https://www.facebook.com/xinze.wang.7"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/xinze-wang-89bb38101/"
  stackoverflow  = "https://stackoverflow.com/users/5822375/daveedo"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/DavidNeko"
  # wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  
  # [[params.friend_link]]
  # title = "Linda的博客"
  # href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "V2EX"
  href =  "https://www.v2ex.com/"
  [[params.bookmark_link]]
  title = "InfoQ"
  href =  "https://www.infoq.com/"
  [[params.bookmark_link]]
  title = "FreeBuf"
  href = "http://www.freebuf.com/"
  [[params.bookmark_link]]
  title =  "SegmentFault"
  href = "https://segmentfault.com/"
  
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true